config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # devise_for :admins
  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"
  root "articles#index"
  post "forgot_pass" => "users#find_pass"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :articles do
  	resources :comments, controller: 'articles/comments'
  end

  resources :pictures
  namespace :admin do
    resources :users  
    resources :articles do
      resources :comments
    end
    root 'admin#show'
  end
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy 
	has_many :pictures, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank
	def self.search_articles(search)
		if search.present? 
    	where("LOWER(title) LIKE ? OR LOWER(text) LIKE ?", "%#{search.downcase}%","%#{search.downcase}%")
  	else
  		all
    end
  end
  	
	# validate :validate_title


	# def validate_title
	# 	if !self.title.present?
	# 		errors.add(title: "Wrong!!!!!!")
	# 	end
	# end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
	def show
		@article = Article.find(params[:id])
	end
	def index
		@articles = Article.order('created_at desc').paginate(:page => params[:page], :per_page => 7 )
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to admin_articles_path(@article)
	  else
	    render 'edit'
	  end
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to admin_articles_path
	end
	private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  before_action :set_article
  
  def create
    if params[:body].present?
      @comment = @article.comments.create(body: params[:body], user_id: current_user.id)
    end
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.js
    end
  end

  def update
    @comment = @article.comments.find(params[:id])
    if @comment.update(body: params[:comment][:body])
      respond_to do |format|
        format.js
      end
    else
        redirect_to article_path(@article, flag: true)
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html  {redirect_to article_path(Article.all.find(params[:article_id]))}
      format.js
    end
  end
  private

  def set_article
    @article = Article.find(params[:article_id])
    
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:update, :edit, :destroy]
  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.where.not(id: nil).order('created_at DESC')
  end

  

  def index
    if params[:search].present?
      @articles = Article.search_articles(params[:search])
      if @articles.present?
        respond_to do |format|
          format.js
        end
      else
        # TODO
      end
    else
      @articles = Article.all
    end
    @article = Article.new
    if @articles.present? 
      @articles = @articles.order('created_at desc').paginate(:page => params[:page], :per_page => 6 )
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      if params[:article][:image]
        params[:article][:image].each { |image|
          @article.pictures.create(image: image)
        }
      end

    end
    if @article.errors.present?
      flash[:warning] = @article.errors.full_messages.join(", ")
      render :new
    else 
      respond_to do |format|
        format.html { redirect_to articles_path }
        format.js
      end
    end
  end

  def edit; end

  def update   
    respond_to do |format|
      if @article.update(article_params)
        if params[:article][:image]
          params[:article][:image].each { |image|
            @article.pictures.create(image: image)
          }
        end
        if params[:page_index] == "true"
          format.js
        else
          format.html { redirect_to article_path(@article) }
        end
      else
        format.html { render 'edit' }
        format.js
      end
    end
  end
  
  def destroy
    @article.destroy
    respond_to do |format|
      if params[:page_index]
        format.js
      else
        format.html { redirect_to articles_path }
      end
    end
  end
  private
  def article_params
    params.require(:article).permit(:title, :text, :pictures)
  end
  
  def set_article
    @article = current_user.articles.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Edit article</h1>
		<%= form_with(model: @article, url: admin_article_path(@article), local: true) do |form| %>
		  <p>
		    <%= form.label :title %><br>
		    <%= form.text_field :title %>
		  </p>
		  <p>
		    <%= form.label :text %><br>
		    <%= form.text_area :text %>
		  </p>
		  <p>
		    <%= form.submit %>
		  </p>
		<% end %>
		<%= link_to 'Back', admin_articles_path %>
	</div>
</div>

app/views/admin/articles/index.html.erb
<div class="container">

	<h1>List Article</h1>
	<table class="table">
	  <thead>
	  	<th>ID</th>
	    <th>Title</th>
	    <th>Content</th>
	    <th>Created At</th>
	    <th>Updated At</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </thead>
	  <tbody>
	    <% @articles.each do |article| %>
  			<tr>
  				<td><%= article.id %></td>
  				<td><%= article.title.truncate(20) %></td>
			    <td><%= article.text.truncate(50) %></td>
			    <td><%= time_ago_in_words(article.created_at) + " ago"%></td>
			    <td><%= time_ago_in_words(article.updated_at) + " ago"%></td>
        		<td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
			    <td><%= link_to "Show", admin_article_path(article) %></td>
			    <td><%= link_to "Delete Article",  admin_article_path(article) ,
        				method: :delete,
        				data: {confirm: "Are you sure?"} %></td>
   			</tr>
   		<% end %>
	  </tbody>
	</table>
	<p><%= will_paginate @articles %></p>


</div>

app/views/admin/articles/show.html.erb
<div class="container">
	<div class="row">
		<div class="dropdown">
		  	<a data-toggle="dropdown" href="#"><h1><%= @article.title %></h1></a>
		  	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		  		<li role="presentation"><a role="menuitem" tabindex="-1">
        			<td><%= link_to 'Edit', edit_admin_article_path(@article) %></td>
		    	</a></li>
		    	<li role="presentation"><a role="menuitem" tabindex="-1">
        			<td><%= link_to "Delete Article",  admin_article_path ,
        				method: :delete,
        				data: {confirm: "Are you sure?"} %></td>
		    	</a></li>

		    </ul>
		</div>
	</div>
	<h4>Content: <%= @article.text %></h4>
	<h5>Author: <%=  link_to User.find(@article.user_id).full_name , admin_user_path(User.find(@article.user_id)) %></h5>

	
	
	<h3>All Comments:</h3>
	<% @article.comments.each do |comment| %>
		<div class="row">
			<div class="col-md-8">
				<% if comment.id.to_s == params[:id_comment_edit] %>	
					<%= form_with(model: comment, url: admin_article_comment_path(@article, comment), local: true) do |form| %>
						<div class="row">
							<div class="col-md-2">
								<strong><%= User.find(comment.user_id).full_name + ":" %></strong>
							</div>
							<div class="col-md-8">
							    <%= form.text_area :body %>
							</div>
							<div class="col-md-2">
							   	<p><%= form.submit :Comment %></p>
							</div>
						</div>
					<% end %>
				<% elsif comment.id.present? == true %>
					<p class="outset">
						<strong><%= User.find(comment.user_id).full_name + ": " %></strong>
						<%= comment.body %>
					</p>
				<% end %>
			</div>
			<% if comment.id.to_s != params[:id_comment_edit] %>	
				<div class="col-md-4">
					<div class="dropdown">
					  <a data-toggle="dropdown" href="">...</a>
					  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
					  	<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Flag</a></li>
					  	<li role="presentation"><a role="menuitem" tabindex="-1" href="#">Reply</a></li>
						
				    	<li role="presentation"><a role="menuitem" tabindex="-1">
		        			<td><%= link_to 'Edit', edit_admin_article_comment_path(@article,id_comment: comment.id) %></td>
				    	</a></li>
				    	<li role="presentation" class="divider"></li>
				    	<li role="presentation"><a role="menuitem" tabindex="-1">
				    		<td><%= link_to "Delete", admin_article_comment_path(@article,id_comment: comment.id),
						  		method: :delete,
						  		data: {confirm: "Are you sure?"} %></td>

					  </ul>
					</div>
				</div>
			<% end %>
		</div>

	<% end %>
	<div class="row">
		<%= link_to 'Back', admin_articles_path %>
	</div>
</div>