config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # devise_for :admins
  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"
  root "articles#index"
  post "forgot_pass" => "users#find_pass"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :articles do
  	resources :comments, controller: 'articles/comments'
  end

  resources :pictures
  namespace :admin do
    resources :users  
    resources :articles do
      resources :comments
    end
    root 'admin#show'
  end
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy 
	has_many :pictures, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :all_blank
	def self.search_articles(search)
		if search.present? 
    	where("LOWER(title) LIKE ? OR LOWER(text) LIKE ?", "%#{search.downcase}%","%#{search.downcase}%")
  	else
  		all
    end
  end
  	
	# validate :validate_title


	# def validate_title
	# 	if !self.title.present?
	# 		errors.add(title: "Wrong!!!!!!")
	# 	end
	# end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
	def show
		@article = Article.find(params[:id])
	end
	def index
		@articles = Article.order('created_at desc').paginate(:page => params[:page], :per_page => 7 )
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to admin_articles_path(@article)
	  else
	    render 'edit'
	  end
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to admin_articles_path
	end
	private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  before_action :set_article
  
  def create
    if params[:body].present?
      @comment = @article.comments.create(body: params[:body], user_id: current_user.id)
    end
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.js
    end
  end

  def update
    @comment = @article.comments.find(params[:id])
    if @comment.update(body: params[:comment][:body])
      respond_to do |format|
        format.js
      end
    else
        redirect_to article_path(@article, flag: true)
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html  {redirect_to article_path(Article.all.find(params[:article_id]))}
      format.js
    end
  end
  private

  def set_article
    @article = Article.find(params[:article_id])
    
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:update, :edit, :destroy]
  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.where.not(id: nil).order('created_at DESC')
  end

  

  def index
    if params[:search].present?
      @articles = Article.search_articles(params[:search])
      if @articles.present?
        respond_to do |format|
          format.js
        end
      else
        # TODO
      end
    else
      @articles = Article.all
    end
    @article = Article.new
    if @articles.present? 
      @articles = @articles.order('created_at desc').paginate(:page => params[:page], :per_page => 6 )
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      if params[:article][:image]
        params[:article][:image].each { |image|
          @article.pictures.create(image: image)
        }
      end

    end
    if @article.errors.present?
      flash[:warning] = @article.errors.full_messages.join(", ")
      render :new
    else 
      respond_to do |format|
        format.html { redirect_to articles_path }
        format.js
      end
    end
  end

  def edit; end

  def update   
    respond_to do |format|
      if @article.update(article_params)
        if params[:article][:image]
          params[:article][:image].each { |image|
            @article.pictures.create(image: image)
          }
        end
        if params[:page_index] == "true"
          format.js
        else
          format.html { redirect_to article_path(@article) }
        end
      else
        format.html { render 'edit' }
        format.js
      end
    end
  end
  
  def destroy
    @article.destroy
    respond_to do |format|
      if params[:page_index]
        format.js
      else
        format.html { redirect_to articles_path }
      end
    end
  end
  private
  def article_params
    params.require(:article).permit(:title, :text, :pictures)
  end
  
  def set_article
    @article = current_user.articles.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="post_<%= article.id%>">	
	<div class="post-preview">
	  <h2 class="post-title">
	    <%= link_to article.title, article_path(article), :'data-toggle' => :tooltip, :title => article.created_at.strftime("At %r") %>
	  </h2>
	  <h3 class="post-subtitle">
	    <%= article.text.truncate(100) %>
	  </h3>
	  <p class="post-meta">Posted by
	    <a><%= link_to article.user.full_name, user_path(article.user) %></a>
	    <%= article.created_at.strftime("on %B %d, %Y") %></p>
	  <% if current_user.id == article.user_id %> 
			<div class="btn-group" role="group" aria-label="...">
				<button type="button" class="btn btn-warning" data-toggle ="modal" data-target="#myupdatepost_<%= article.id %>">Edit</button>
				<%= link_to "Destroy", article_path(:id => article.id ,:page_index => true) ,method: :delete , data: {confirm: "Are you sure?"}, class: "btn btn-danger" , remote: true%>
			</div>
		<% end %>

		<!-- Modal -->
		<div class="modal fade" id="myupdatepost_<%= article.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<%= form_for(article, :method => :put, remote: true ) do |f|%>
				<%= hidden_field_tag :page_index, true %>
			  <div class="modal-dialog modal-lg" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h4 class="modal-title" id="myModalLabel">Edit</h4>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			      </div>
			      <div class="modal-body">
			        <div class="field">
	              <%= f.label :title%><br>
	              <%= f.text_field :title, class: "form-control "%>
	            </div>
	            <div class="field">
	              <%= f.label :text %><br>
	              <%= f.text_area :text, class: "form-control "%>
	            </div>
	            <div class="control-group">
				        <%= f.label :pictures, :class => 'control-label' %>
				        <div class="controls">
				          <%= f.file_field :image, type: :file, multiple: true %>
				        </div>
					    </div>
			      </div>
			      <div class="modal-footer">
			        <button type="button" id="myupdatebutton_<%= article.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
			        <%= submit_tag "Update", class: "btn btn-primary" %>
			      </div>
			    </div>
			  </div>
			<% end %>
		</div>
	</div>
	<hr>
</div>

app/views/articles/_comment.html.erb
<% if comment.id.present? == true %>
	<div class="row" id="comment_<%= comment.id %>">
		<div class="col-md-10 ">
			<div class="comment mb-2 row ">
	      <div class="comment-avatar col-md-1 col-sm-2 text-center pr-1">
	      		<% if comment.user.avatar.present? %>
					  	<%= link_to image_tag(comment.user.avatar.url, :class => "mx-auto rounded-circle img-fluid", alt: "avatar"), user_path(comment.user)%>
				  	<% else %>
					  	<%= link_to image_tag("user.png", :class => "mx-auto rounded-circle img-fluid", alt: "avatar"), user_path(comment.user)%>
				  	<% end %>
	      </div>
	      <div class="comment-content col-md-11 col-sm-10">
	          <h6 class="small comment-meta"><strong><%= link_to comment.user.full_name, user_path(comment.user) %><%= comment.created_at.strftime(" - On %a, %X")%></strong></h6>
	          <div class="comment-body " >
	            <p id="edit_cmt_<%= comment.id %>"><%= comment.body %></p>
	            <p><% if  current_user.id == comment.article.user_id || current_user.id  == comment.user_id %>
								<%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, '#', class: "text-right small", "data-toggle": "modal" ,"data-target": "#editmycmt_#{ comment.id }" ,id: "edit_cmt" %>
								<span> / </span>
								<%= link_to '<i class="fa fa-remove"></i> Delete'.html_safe, article_comment_path(article_id: comment.article_id,id: comment.id), class: "text-right small", method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
								<!-- Modal edit cmt -->
									<%= form_for(comment, url: article_comment_path(comment.article, comment),remote: true) do |f| %>
									  <div class="modal fade" id="editmycmt_<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
									    <div class="modal-dialog" role="document">
									      <div class="modal-content">
									        <div class="modal-header">
									          <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
									          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
									        </div>
									        <div class="modal-body">
														<%= f.text_area :body , :class => 'form-control' %>
									        </div>
									        <div class="modal-footer">
									          <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
														<p><%= f.submit :Comment ,:class => "btn btn-primary" %></p>
									        </div>
									      </div>
									    </div>
									  </div>
									<% end %>
									<!-- end modal edit comment -->
							<% end %>
	            </p>
	          </div>
	      </div>
	  	</div>	
		</div>
	</div>
<% end %>

app/views/articles/_form_article.html.erb
<%= form_with(model: @article, local: true) do |form| %>

    <div class="form-group">
    <%= form.text_field :title, class: "form-control", placeholder: "Write Title" %>
    </div>
    <div class="form-group">
    <%= form.text_area :text, class: "form-control", placeholder: "Write Content" %>
    </div>
    
    <div class="control-group">
        <%= form.label :pictures, :class => 'control-label' %>
        <div class="controls">
            <%= form.file_field :image, type: :file, multiple: true %>
        </div>
    </div>
    <%= form.submit  %>
    <div class="pull-right">
        <div class="btn-group">
            <button type="button" class="btn btn-default"><i class="fa fa-pencil"></i> Text</button>
            <button type="button" class="btn btn-default"><i class="fa fa-file-image-o"></i> Image</button>
            <button type="button" class="btn btn-default"><i class="fa fa-file-video-o"></i> Video</button>
        </div>
    </div>
<% end %>

app/views/articles/_header_article.html.erb
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= article.title %></h1>
          <p class="meta">Posted by
            <%= article.user.full_name %>
            <%= article.created_at.strftime("on %B %d, %Y") %></p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/articles/create.js.erb
	$("#mynewpost").modal('hide');
$(".title_article").val('');
$(".content_article").val('');
$(".image_article").val('');
$(".container_posts").prepend('<%= j render @article %>');
$('#post_<%= @article.id%>').hide().fadeIn(1000);

app/views/articles/destroy.js.erb
$('#post_<%= @article.id%>').fadeOut(500, function(){
	$(this).remove();
});

app/views/articles/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Edit your article</h3>
	          </div>
	          <div class="panel-body">
				<%= render 'form_article' %>
	          </div>
	        </div>
    	</div>
    	<div class="col-md-4">
            <div class="panel panel-default friends">
              <div class="panel-heading">
                <h3 class="panel-title">My Friends</h3>
              </div>
              <div class="panel-body">
                
                <div class="clearfix"></div>
                <a href="#" class="btn btn-primary">View All Friends</a>
              </div>
            </div>
            <div class="panel panel-default groups">
              <div class="panel-heading">
                <h3 class="panel-title">Latest Groups</h3>
              </div>
              <div class="panel-body">
                
              </div>
            </div>
         </div>


	</div>

    
	<div class="row">
	  	<%= link_to "Back", articles_path(current_user) %>
	</div>
</div>

app/views/articles/index.html.erb
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Vinova's Blog</h1>
          <span class="subheading">Help you connect with the people in your life.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto ">
      <% if @articles.present? %>
        <div class="show_articles container_posts">
          <%= render @articles %>
          <%= will_paginate @articles,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        </div>      
      <% end %>
    </div>
    <div class="col-lg-4 col-md-2 mx-auto">
    	<div id="search_box">
        <%= form_tag articles_path, method: :get, remote: true do %>
          <div class="form-group">
            <%= text_field_tag :search,"", class: "search_input" ,placeholder: "Type Here..."%>

          </div>
        <% end %>
      </div>
      Field nay dung de Quang Cao
      <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#mynewpost" id="create_post">
        New Article
      </button>
    </div>
  </div>
</div>
<!-- Modal -->
<%= form_for(@article, remote: true) do |f| %>
  <div class="modal fade" id="mynewpost" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Article</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= f.label :title%><br>
            <%= f.text_field :title, class: "form-control title_article"%>
          </div>
          <div class="field">
            <%= f.label :text %><br>
            <%= f.text_area :text, class: "form-control content_article"%>
          </div>
          <div class="control-group">
            <%= f.label :pictures, :class => 'control-label' %>
            <div class="controls">
              <%= f.file_field :image, type: :file, multiple: true, class: "image_article" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
          <%= submit_tag "Create", class:"btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
$('document').ready(function() {
  setTimeout(function() {
    $('.alert').slideUp();
  }, 500);
});
</script>

app/views/articles/index.js.erb
// $(".show_articles").hide();
$(".search_input").val('');
// $(".show_articles").prepend("<%= j render @articles %>");
$(".show_articles").html('<%= j render @articles %>');
$(".show_articles").append('<%= will_paginate @articles,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>');

app/views/articles/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Add your article</h3>
	          </div>
	          <div class="panel-body">
				<%= render 'form_article' %>
	          </div>
	        </div>
    	</div>
    	<div class="col-md-4">
            <div class="panel panel-default friends">
              <div class="panel-heading">
                <h3 class="panel-title">My Friends</h3>
              </div>
              <div class="panel-body">
                
                <div class="clearfix"></div>
                <a href="#" class="btn btn-primary">View All Friends</a>
              </div>
            </div>
            <div class="panel panel-default groups">
              <div class="panel-heading">
                <h3 class="panel-title">Latest Groups</h3>
              </div>
              <div class="panel-body">
                
              </div>
            </div>
         </div>
	</div>
	<div class="row">
	  	<%= link_to "Back", articles_path(current_user) %>
	</div>
</div>

app/views/articles/show.html.erb
<%= render "header_article" , article: @article %>
<section class="showcase">
  <div class="container-fluid p-0">
		<div class="row">
		  <div class="col-lg-4 text-white"> 
		  	<% if @article.pictures.present? %>
			  	<%= link_to image_tag(@article.pictures.first.image.url, :class => "img-thumbnail image_post"), @article.pictures.first.image.url, "data-lightbox": "gallery" , "data-title": "Sample Image 1"%>
		  	<% else %>
				  <%= image_tag("nothing_here_yet.png", :class => "img-thumbnail image_post")%>
		  	<% end %>
		  </div>
		  <div class="col-lg-8 my-auto showcase-text">
		    <p class="lead mb-0"><%= @article.text %></p>
	    	<% if current_user.id == @article.user_id %> 
					<div class="btn-group" role="group" aria-label="...">
						<button type="button" class="btn btn-warning" data-toggle ="modal" data-target="#myupdatepost_<%= @article.id %>" id="edit_post" >Edit</button>
						<%= link_to "Destroy", @article, method: :delete,data: {confirm: "Are you sure?"}, class: "btn btn-danger",id: "delete_post", remote: true%>
					</div>
				<% end %>
		  </div>
		</div>
	</div>
</section>
<div class="row">
	<% if @article.pictures.present? %>
	  <% @article.pictures.where.not(id: @article.pictures.first.id).each_with_index do |pic,index| %>
	  	<div class="col-md-4">
	  		<%= link_to image_tag(pic.image.url, :class => "img-thumbnail image_post img-hidden"), pic.image.url, "data-lightbox": "gallery" , "data-title": "Sample Image " + (index+1).to_s%>
	  	</div>
	  <% end %>
  <% end %>
</div>
		<!-- Modal -->
<div class="modal fade" id="myupdatepost_<%= @article.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<%= form_for(@article, :method => :put, remote: true) do |f|%>
	  <div class="modal-dialog modal-lg" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title" id="myModalLabel">Edit</h4>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	      </div>
	      <div class="modal-body">
	        <div class="field">
            <%= f.label :title%><br>
            <%= f.text_field :title, class: "form-control "%>
          </div>
          <div class="field">
            <%= f.label :text %><br>
            <%= f.text_area :text, class: "form-control "%>
          </div>
          <div class="control-group">
		        <%= f.label :pictures, :class => 'control-label' %>
		        <div class="controls">
		          <%= f.file_field :image, type: :file, multiple: true %>
		        </div>
			    </div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" id="myupdatebutton_<%= @article.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= submit_tag "Update", class: "btn btn-primary" %>
	      </div>
	    </div>
	  </div>
	<% end %>
</div>

<hr>

<div class="container">
  <div class="row">
    <div class="col-md-9">
    	<h3 class="mb-2">Comments</h3>
			<%= form_tag article_comments_path(@article), method: :post, remote: true do |form| %>
				<div class="comment-form ">
					<form class="form-inline">
						<div class="form-group">
							<%= text_area_tag :body , '', :class => 'form-control comment_body' %>
						</div>
						<p><%= submit_tag :Comment , :class => "btn btn-primary" %></p>
					</form>
				</div>
			<% end %>
			<hr>
		</div>
    <div class="comments col-md-10 offset-md-1" id="comments">
    	<div class="container_comments">
	    	<br>
				<% @comments.each do |comment| %>
					<%= render 'comment', comment: comment %>
				<% end %>
			</div>
		</div>
  </div>
</div>

app/views/articles/update.js.erb
$("#myupdatepost_<%= @article.id %>").modal('hide');
var a_link = "<a data-toggle='tooltip' title='' href='/articles/<%= @article.id %>' data-original-title='"+"<%= @article.created_at.strftime('At %r')%>"+"'><%= @article.title %></a>";
$("#post_<%= @article.id%>").find('.post-title').html(a_link);
$("#post_<%= @article.id%>").find('.post-subtitle').text('<%= @article.text.truncate(100) %>');
$('[data-toggle="tooltip"]').tooltip();