config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  # devise_for :admins
  get "login" => "session#new"
  post "login" => "session#create"
  delete "logout" => "session#destroy"
  root "articles#index"
  post "forgot_pass" => "users#find_pass"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :articles do
  	resources :comments, controller: 'articles/comments'
  end

  resources :pictures
  namespace :admin do
    resources :users  
    resources :articles do
      resources :comments
    end
    root 'admin#show'
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :articles, dependent: :destroy 
	has_many :comments, dependent: :destroy
	has_attached_file :avatar, styles: { large: "600x600>" , medium: "300x300>", thumb: "230x230#"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :articles, allow_destroy: true, reject_if: :all_blank
  validates_presence_of :full_name, :name
  validates_uniqueness_of :name

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def new
    @user = User.new
  end
  def create
    
  end
	def index
		@users = User.order('created_at asc').paginate(:page => params[:page], :per_page => 5)
	end
	def show
		# if !session[:user_id].present?
		# 	redirect_to login_path
		# end
		@user = User.find(params[:id])
		@articles = @user.articles.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		user = User.find(params[:id])
		if params[:user][:new_password].present? || params[:user][:confirm_new_password].present?
			if params[:user][:new_password] != params[:user][:confirm_new_password] 
				flash[:warning] = "Two password don't match."
	  			render :edit
			end
		end
	  	if user && user.update(user_params)
	   		if params[:user][:new_password].present?
	   			user.password = params[:user][:new_password]
	   			user.password_confirmation = params[:user][:confirm_new_password]
	   		end
	   		if user.save
	   			flash[:success] = "Update successed"
	   			redirect_to admin_users_path
	  		else
	  			flash[:danger] = "Update failed"
	  			render :edit
	  		end
	  	end
	end
	def destroy
		@user = User.find_by id: params[:id]
		@user.destroy
		redirect_to admin_users_path
	end
	private
	def user_params
		params.require(:user).permit :name, :full_name, :email, :password, :password_confirmation
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login, only: [:new,:create,:find_pass]
	def index
		@users = User.where.not(id: current_user.id).order('created_at asc').paginate(:page => params[:page], :per_page => 5)
	end
	def show
		# if !session[:user_id].present?
		# 	redirect_to login_path
		# end
    @article = Article.new
		@user = User.find(params[:id])
		@articles = @user.articles.order('created_at desc').paginate(:page => params[:page], :per_page => 5)
	end
	def new
		@user = User.new
	end
	def create
		#params[:user][:name].include?(' ')
		# @user = User.new user_params
		# if @user.name.include?(' ')
		# 	flash[:warning] = "Have space in your name"
		# 	render :new
		# elsif User.find_by(name: params[:user][:name]).present?
		# 	flash[:warning] = "Register failed. Your name have existed."
		# 	render :new
		# elsif @user.save
		# 	flash[:success] = "Register success"
		# 	redirect_to users_path
		# else
		# 	flash[:warning] =  "Register failed"
		# 	render :new
		# end
		# if params[:user][:name].include?(' ') || User.find_by(name: params[:user][:name]).present?
		# 	render :new
		# else
		# 	@user = User.new user_params
		# 	if @user.save
				
		# 	end
		# end
		message = params[:user][:name].include?(' ') ? "Have space in your name" : 
					(User.find_by(name: params[:user][:name]).present? ? "Register failed. Your name have existed." 
							: nil)
		@user = User.new user_params
		@user.authorities = false
		unless is_a_valid_email?(params[:user][:email])
			message = "Email invalid"
		end
		if message.present?
			flash[:warning] = message
			render :new
		else
			if @user.save
				flash[:success] = "Register success"
				redirect_to login_path
			else
				flash[:warning] =  "Register failed"
				render :new
			end
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		user = User.find(params[:id])
		if params[:user][:avatar].present?
			user.avatar = params[:user][:avatar]
			user.save
			redirect_to edit_user_path(user)
		end
		if params[:user][:new_password].present? || params[:user][:confirm_new_password].present?
			if params[:user][:new_password] != params[:user][:confirm_new_password] 
				flash[:warning] = "Two password don't match."
	  			render :edit
			end
		end
	  	if user && user.authenticate(params[:user][:password]) && user.update(user_params)
	   		if params[:user][:new_password].present?
	   			user.password = params[:user][:new_password]
	   			user.password_confirmation = params[:user][:confirm_new_password]
	   		end
	   		if user.save
	   			flash[:success] = "Update successed"
	   			redirect_to edit_user_path
	  		else
	  			flash[:danger] = "Update failed"
	  			render :edit
	  		end
	  	end
	end
	def destroy
		@user = User.find(params[:id])
    if params[:delete_all_articles]
      @user.articles.all.destroy_all
      redirect_to articles_path
    else
  		log_out
  		@user.destroy
  		redirect_to login_path
		end

		
	end
	def find_pass
		user = User.find_by name: params[:user][:name]
		message = !user.present? ? "User name not exist." : 
			( user.email != params[:user][:email] ? "Email Invalid." : 
				( user.update(user_params) && user.save ? "Successed" : "Two password don't match." ))
		# unless user.present?
		# 	flash[:warning] = "User name not exist."
		# 	redirect_to login_path(flag: true)
		# end
		# if user.email != params[:user][:email]
		# 	flash[:warning] = "Email Invalid."
		# 	redirect_to login_path(flag: true)	
		# end
		# if user.update(user_params)
	 #   		if user.save
	 #   			flash[:success] = "Successed"
	 #   			redirect_to login_path
	 #  		else
		# 		flash[:warning] = "Two password don't match."
		# 		redirect_to login_path(flag: true)	
	 #  		end
	 #  	end
	 	if message == "Successed"
	 		flash[:success] = message
	 		redirect_to login_path
	 	else
	 		redirect_to login_path(flag: true,message: message)	
	 	end
	end
	private
	def user_params
		params.require(:user).permit :name, :full_name, :email, :password, :password_confirmation, :avatar
	end
	
	
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/admin/users/_list_user.html.erb
<tr> 
  <td><%= link_to user.name, admin_user_path(user) %></td>
  <td><%= user.full_name %></td>
  	<td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
  	<td><%= link_to "Delete User", admin_user_path(user),
  		method: :delete,
  		data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/admin/users/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Edit info</h1>
		<%= form_with(model: @user, url: admin_user_path, method: :put)  do |f| %>
      <div class="form-group">
        <%= f.label :"full_name" %>
        <%= f.text_field :full_name, placeholder: "Enter full name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"email" %>
        <%= f.text_field :email, placeholder: "Enter email ", class: "form-control" %>
      </div>
      <input type="checkbox" id="checkbox">Change Password 
      <div id="change_pass">
        <div class="form-group">
          <%= f.label :new_password %>
          <%= f.password_field :new_password, placeholder: "Enter your new password",
            class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :confirm_new_password %>
          <%= f.password_field :confirm_new_password, placeholder: "Comfirm your new password",
            class: "form-control" %>
        </div>
      </div>
      <div class="text-center">
        <%= f.submit "Update", class: "btn btn-info col-lg-12" %>
      </div>
    <% end %>
		<p class="text-right"><%= link_to "Delete User",  admin_user_path(@user),
                                    method: :delete,
                                    data: {confirm: "Are you sure?"} %></p>
		<p class="text-left"> <%= link_to 'Back', admin_users_path %> </p>
	</div>
</div>
<script>
    $('#change_pass').hide();
    $('#checkbox').click(function(){
        if ($(this).is(":checked")) {
            console.log("checked")
            $('#change_pass').show();
        }
        else {
            console.log("unchecked")
            $('#change_pass').hide();
        }
    })
</script>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 form-group">
      <label for="">List Users</label>
      <table class="table">
        <thead>
          <th>User Name</th>
          <th>Full Name</th>
          <th></th>
          <th></th>
          <th></th>
        </thead>
        <tbody>
          <%#= render @users %>
            <% @users.each do |user| %>
                    <%= render "list_user", user: user %>
            <% end %>
            <p><%= will_paginate @users %></p>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
	<h1><%= @user.name %>'s Blog</h1>
	<table class="table">
		<h1><%= @user.name %>'s Articles</h1>
	  <thead>
	    <th>Title</th>
	    <th>Content</th>
	    <th></th>
	  </thead>
	  <tbody>
		<% @articles.each do |article| %>
		  <tr>
		    <td><%= link_to article.title, admin_article_path(article) %></td>
		    <td><%= article.text.truncate(50) %></td>
		   
		 	
		  </tr>
		<% end %>
	  </tbody>
	</table>

	<p><%= will_paginate @articles %></p>
	
</div>